### ISSUE TITLE
Attempted to load class "Sms77SyliusPlugin" from namespace "Sms77\SyliusPlugin". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by langziyang** [sms77io/sylius-plugin#1]
i added Sms77\SyliusPlugin\Sms77SyliusPlugin::class => ['all' => true], the i got error:
Attempted to load class "Sms77SyliusPlugin" from namespace "Sms77\SyliusPlugin". Did you forget a "use" statement for another namespace?

**Comment by matthiez** [comment]
Hi,

I think the README is lacking here.

You need to install the package via composer first:
Run ```composer require sms77/sylius-plugin``` in a terminal and go on with the steps from the README.
